version: '3'
services:
  duckdb-ui:
    # https://hub.docker.com/r/kudaw/duckdb-ui
    image: kudaw/duckdb-ui:1.3.2
    networks:
      - docker_network
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - duckdb_data:/root/data
      - ..:/workspaces/devcontainer-duckdb-ui:cached

volumes:
  duckdb_data:

networks:
  docker_network:
    #driver: bridge
    #driver: overlay
    external: false
    name: docker_network
    attachable: true
